<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'An error occurred while installing Rights.' => 'Ocorreu um erro ao tentar instalar o Rights',
  'Application authorization manager must extend the RDbAuthManager class.' => 'A aplicação authorization manager tem que extender da classe RDbAuthManager',
  'Application web user must extend the RWebUser class.' => 'A apliacação web user tem que extender da classe RWebUser',
  'Error' => 'Erro',
  'Please try again or consult the documentation.' => 'Por favor tente novamente ou consulte a documentação',
  'Congratulations!' => 'Parabéns!',
  'Install Rights' => 'Instalar Rights',
  'No' => 'Não',
  'Notice: All your existing data will be lost.' => 'Advertencia: Todos os dados existentes serão deletados.',
  'Please confirm if you wish to reinstall.' => 'Por favor confirme se deseja reinstalar.',
  'Rights has been installed succesfully.' => 'Rights instalado com sucesso.',
  'Rights is already installed!' => 'Rights já está instalado!',
  'Yes' => 'Sim',
  'You can start by generating your authorization items' => 'Pode começar criando seus próprios objetos de autorização',
  'You must be logged in to install Rights.' => 'Você precisa estar conectado para instalar Rights.',
  'here' => 'aqui',
);
